### ISSUE TITLE
Trade Intensity indicator (TII)

### ISSUE THREAD

**Issue by Giocaso** [LastAncientOne/Stock_Analysis#10]
Hi all, it would be useful to also have the Trade Intensity Indicator (TII) in the Technical_Analysis.xlsx spredsheet, do you think it is possible to implement it? many tks

**Comment by LastAncientOne** [comment]
Hi there,
I will create one for python and excel.

**Comment by Giocaso** [comment]
Thank you, that's very kind of you.

**Comment by Giocaso** [comment]
Hello, when you have some time do you plan to develop the TII for excel as you wrote? 
Tks in advanced

**Comment by LastAncientOne** [comment]
I added in excel and python.
