### ISSUE TITLE
Considered including Options?

### ISSUE THREAD

**Issue by ApurvShah007** [LastAncientOne/Stock_Analysis#2]
You have done a great job including almost everything there is. I would love to help you with this repo and include Options and options trading strategies in this wonderful repo. @LastAncientOne

**Comment by LastAncientOne** [comment]
Hi. I would like to work with you on the options or other trading strategies.  I am trying to add more options strategies but I have been busy working on other codes.  @ApurvShah007

**Comment by ApurvShah007** [comment]
@LastAncientOne I have been implementing many different strategies for options trading and would love to help you add on this.

**Comment by ApurvShah007** [comment]
I also work on portfolio analysis and various optimization methods and would love to contribute that as well to this repository. @LastAncientOne

**Comment by ahoskam** [comment]
The Yahoo api is broken.  What format is the data in that you need.  The updated matlab function pulls the data in differently.  https://www.mathworks.com/matlabcentral/fileexchange/18458-hist_stock_data-start_date-end_date-varargin
