### ISSUE TITLE
RSI.ipynb: TypeError: dtype '<class 'datetime.date'>' not understood

### ISSUE THREAD

**Issue by kenorb** [LastAncientOne/Stock_Analysis#3]
First of all, thanks for this large compendium of technical indicators, it's very useful.

I'm trying to run `RSI.ipynb` and when opened and ran in Colab, and I've got the following error:

> TypeError: dtype '<class 'datetime.date'>' not understood

in the following cell:

```
from matplotlib import dates as mdates
import datetime as dt

dfc = df.copy()
dfc['VolumePositive'] = dfc['Open'] < dfc['Adj Close']
#dfc = dfc.dropna()
dfc = dfc.reset_index()
dfc['Date'] = mdates.date2num(dfc['Date'].astype(dt.date)) // <!-- Issue with this line.
dfc.head()
```

My questions:

- What version of `datetime` you've used to run this notebook?
- What do you suggest to fix it? Downgrading datetime to a different version, or the code should fixed forward?

Colab: https://colab.research.google.com/github/LastAncientOne/Stock_Analysis_For_Quant/blob/master/Python_Stock/Technical_Indicators/RSI.ipynb

Thanks.

**Comment by kenorb** [comment]
Fixed by changing:

```
dfc['Date'] = mdates.date2num(dfc['Date'].astype(dt.date))
```

to:

```
dfc['Date'] = mdates.date2num(pd.to_datetime(dfc['Date']))
```

Related: https://github.com/pandas-dev/pandas/issues/25730

**Comment by LastAncientOne** [comment]
Yes that correct.

If you look at my latest TA, you will see the update.
