### ISSUE TITLE
pyflux  error

### ISSUE THREAD

**Issue by MaPengyu** [LastAncientOne/Stock_Analysis#6]
wind 10
python 3.10

1).pycharm 2022.2:
-note: This error originates from a subprocess, and is likely not a problem with pip.
-error: legacy-install-failure

2).win10 CMD
-note: This error originates from a subprocess, and is likely not a problem with pip.
-error: legacy-install-failure
× Encountered error while trying to install package.
╰─> pyflux

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by LastAncientOne** [comment]
https://github.com/rjt1990/pyflux

Supported on Python 2.7 and 3.5.  I have test it on Python 3.6 and 3.7 on Anaconda. It worked. 

Maybe try install using whl?  https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyflux

Download the whl and install it from there.  

pip install some-package.whl
