### ISSUE TITLE
Python TA HeatMap Analysis/Inference

### ISSUE THREAD

**Issue by shubhamparamhans** [LastAncientOne/Stock_Analysis#7]
Hello @LastAncientOne , you have done really great work in maintaining this repository.
I was wondering if you can share any reference or any reading item so we can understand how to analyse heat map generated by python TA notebook.
As a beginner, the amount of data seems intimidating :)

**Comment by LastAncientOne** [comment]
Hi there,

I will update them and explain them.

Hope you enjoy my work and support me.  You have a great day.
