### ISSUE TITLE
Questions regarding the document

### ISSUE THREAD

**Issue by BradKML** [LastAncientOne/Stock_Analysis#8]
1. For the "lazy portfolio" strategies, what are the fastest way to do backtesting and analysis? Lists like [This](https://www.optimizedportfolio.com/lazy-portfolios/), [This](https://portfolioslab.com/lazy-portfolios), and [This](http://www.lazyportfolioetf.com/) exists https://github.com/LastAncientOne/Stock_Analysis_For_Quant/blob/master/README.md#list-of-portfolio-strategies
2. Are all of the risk factors in [QuantStats](https://github.com/ranaroussi/quantstats#to-view-a-complete-list-of-available-methods-run) essential, or are some of them correlated enough such that some are redundant? https://github.com/LastAncientOne/Stock_Analysis_For_Quant/blob/master/README.md#list-of-risk-adjusted-returns-ratios-measurement
3. Are visualization a good idea for explaining stocks like [PCA](https://github.com/joaotnog/PortfolioVis_py), [Temporal Heatmaps](https://portfoliocharts.com/charts/), [Correlative Networks](https://www.algorhythmblog.be/2022/04/05/visualizing-multicollinearity-in-python/), and [Other Tools](https://www.portfoliovisualizer.com/)?
4. How does the state of the market correlate with risk and return? https://gmarti.gitlab.io/qfin/2020/02/03/sp500-sharpe-vs-corrmats.html

**Comment by LastAncientOne** [comment]
Hi.  

I did not know about "QuantStats" and I will apply to the portfolio and try to explain more about the portfolio.  These strategies are just educational purposes.  Again, I am not a financial advisor, portfolio manager, or accountant. This is not financial advice, investing advice, or tax advice. 

Thank you for provide the information.  I appreciate it.

**Comment by BradKML** [comment]
@LastAncientOne even for education and demonstrative purposes, hopefully there are way of understanding difference of portfolios and visualization that are of use?

**Comment by LastAncientOne** [comment]
Hi there,
I will do my best to explain the different in readme. 

Thank you for the feedback.

**Comment by BradKML** [comment]
Also it would be good to include more stock analysis code examples, but I think those could be separate issues.
